version: "3.9"
services:
  library:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "Bondarenko_206"
      POSTGRES_USER: "Bondarenko_206"
      POSTGRES_PASSWORD: "Bondarenko_206"
    volumes:
      - ./docker/db/scripts/library:/docker-entrypoint-initdb.d
      - ./docker/db/data/library:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  trains:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "Bondarenko_206"
      POSTGRES_USER: "Bondarenko_206"
      POSTGRES_PASSWORD: "Bondarenko_206"
    volumes:
      - ./docker/db/scripts/trains:/docker-entrypoint-initdb.d
      - ./docker/db/data/trains:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  patients:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "Bondarenko_206"
      POSTGRES_USER: "Bondarenko_206"
      POSTGRES_PASSWORD: "Bondarenko_206"
    volumes:
      - ./docker/db/scripts/patients:/docker-entrypoint-initdb.d
      - ./docker/db/data/patients:/var/lib/postgresql/data
    ports:
      - "5434:5432"